import {Platform, StyleSheet} from 'react-native';
import {Fonts, Metrics, Colors} from '../../Themes/';

const styles = StyleSheet.create({
  screenBg: {
    width: Metrics.WIDTH,
    height: '100%',
    backgroundColor: 'black',
  },
  header: {
    height: Metrics.HEIGHT * 0.1,
    backgroundColor: '#fff',
    borderBottomWidth: 0,
    elevation: 0,
    paddingLeft: Metrics.WIDTH * 0.05,
    paddingRight: Metrics.WIDTH * 0.05,
  },
  backArrow: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  backView: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  back: {
    fontSize: 12,
    marginLeft: 15,
  },
  left: {
    flex: 1,
  },
  body: {
    flex: 2,
    alignItems: 'center',
  },
  textTitle: {
    color: Colors.black,
    fontSize: Fonts.moderateScale(20),
    fontWeight: 'bold',
    alignSelf: 'flex-end',
    fontFamily: Fonts.type.helveticaNeueLight,
  },
  content: {
    width: Metrics.WIDTH,
    height: '100%',
    backgroundColor: 'white',
  },
  proimg: {
    marginTop: Metrics.HEIGHT * 0.1,
    flexDirection: 'row',
    alignSelf: 'center',
  },
  TabsView: {
    borderColor: 'rgb(197,185,121)',
    borderBottomWidth: 1,
    width: Metrics.WIDTH * 0.8,
    alignSelf: 'center',
  },
  cardLigne: {
    marginTop: Metrics.HEIGHT * 0.04,
    marginLeft: Metrics.HEIGHT * 0.04,
    marginRight: Metrics.HEIGHT * 0.04,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  cardLigneLast: {
    marginBottom: Metrics.HEIGHT * 0.04,
    marginLeft: Metrics.HEIGHT * 0.04,
    marginRight: Metrics.HEIGHT * 0.04,
    marginTop: Metrics.HEIGHT * 0.04,
    justifyContent: 'center',
    flexDirection: 'row',
  },
  materialTabsView: {
    marginTop: 10,
    width: Metrics.WIDTH * 0.6,
  },
  inputFieldSec: {
    marginTop: Metrics.HEIGHT * 0.04,
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignSelf: 'center',
  },
  preferenceView: {width: Metrics.WIDTH},
  titleText: {
    marginTop: Metrics.HEIGHT * 0.08,
    width: Metrics.WIDTH * 0.9,
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: Metrics.HEIGHT * 0.04,
    alignSelf: 'center',
  },
  nomPrenom: {
    flexDirection: 'row',
    width: Metrics.WIDTH * 0.85,
    height: Metrics.HEIGHT * 0.08,
    justifyContent: 'center',
  },
  itememail: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.7,
    height: Metrics.HEIGHT * 0.08,
  },
  itemeNom: {
    marginRight: 10,
    flex: 0.5,
  },
  itemePrenom: {
    flex: 0.5,
  },
  inputemail: {
    marginLeft: Fonts.moderateScale(-15),
    fontFamily: Fonts.type.sfuiDisplayRegular,
    color: 'black',
  },
  datePickerInput: {
    width: Metrics.WIDTH,
    color: '#000',
    marginLeft: Fonts.moderateScale(-10),
  },
  itempassword: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.7,
    height: Metrics.HEIGHT * 0.08,
  },
  inputpassword: {
    marginLeft: Fonts.moderateScale(-15),
    fontFamily: Fonts.type.sfuiDisplayRegular,
    color: 'black',
  },
  btnMdpVisible: {
    position: 'absolute',
    right: 0,
    bottom: Metrics.HEIGHT * 0.025,
  },
  btnMdpVisible2: {
    position: 'absolute',
    right: 40,
    bottom: Metrics.HEIGHT * 0.025,
  },
  profileImgs: {
    width: Metrics.WIDTH * 0.6,
    height: Metrics.WIDTH * 0.6,
    borderRadius: Metrics.WIDTH * 0.6,
    alignSelf: 'center',
  },
  tabStyle: {},
  scrollStyle: {
    // justifyContent: 'center',
  },
  buttonlogin2: {
    backgroundColor: Colors.yellow,
    alignSelf: 'center',
    height: Metrics.HEIGHT * 0.06,
    width: Metrics.WIDTH * 0.7,
    marginLeft: -Metrics.WIDTH * 0.15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {width: 3, height: 5},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 3,
    marginBottom: Metrics.HEIGHT * 0.2,
  },
  buttonlogin3: {
    backgroundColor: Colors.yellow,
    alignSelf: 'center',
    height: Metrics.HEIGHT * 0.06,
    width: Metrics.WIDTH * 0.7,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: {width: 3, height: 5},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 3,
    marginBottom: Metrics.HEIGHT * 0.2,
  },
  btnText: {
    fontFamily: 'SFUIDisplay-Medium',
    color: 'rgb(159,159,159)',
    fontWeight: 'bold',
    fontSize: Fonts.moderateScale(17),
  },
  suppCompte: {
    width: Metrics.WIDTH * 0.6,
    alignSelf: 'center',
    flexDirection: 'row',
    height: Metrics.HEIGHT * 0.04,
    alignItems: 'center',

    marginBottom: Metrics.HEIGHT * 0.08,
  },
  btnText2: {
    width: Metrics.WIDTH * 0.4,
    fontSize: 13,
    color: 'rgb(159,159,159)',
  },
  card: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.75,
    backgroundColor: 'white',
    shadowOffset: {width: 0, height: 0},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 3,
    marginLeft: -Metrics.WIDTH * 0.15,
    //backgroundColor:'green',
    marginBottom: Metrics.HEIGHT * 0.04,
    paddingBottom: Metrics.HEIGHT * 0.04,
  },
  card2: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.75,
    backgroundColor: 'white',
    shadowOffset: {width: 0, height: 0},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 3,
    //backgroundColor:'green',
    marginBottom: Metrics.HEIGHT * 0.08,
  },
  tabView: {},
  tabBarTextStyle: {
    fontSize: 14,
    fontWeight: 'normal',
    textAlign: 'left',
  },
  underlineStyle: {
    height: 3,
    backgroundColor: 'red',
    borderRadius: 3,
  },
  cameraIcon: {
    position: 'absolute',
    right: -25,
    top: 10,
    width: Metrics.WIDTH * 0.12,
    height: Metrics.WIDTH * 0.12,
    borderRadius: Metrics.WIDTH * 0.6,
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#959595',
    borderWidth: 1,
  },
  cameraCancel: {
    position: 'absolute',
    left: -25,
    top: 10,
    width: Metrics.WIDTH * 0.12,
    height: Metrics.WIDTH * 0.12,
    borderRadius: Metrics.WIDTH * 0.6,
    alignSelf: 'flex-end',
    backgroundColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'red',
    borderWidth: 1,
  },
  nameTxts: {
    color: '#6f6f6f',
    fontSize: Fonts.moderateScale(18),
    textAlign: 'center',
    fontFamily: Fonts.type.SFUIDisplayMedium,
    marginTop: Metrics.HEIGHT * 0.025,
  },
  designtaionTxt: {
    color: '#b7b7b7',
    fontSize: Fonts.moderateScale(14),
    textAlign: 'center',
    fontFamily: Fonts.type.SFUIDisplayRegular,
  },

  followerFollwingLikeBg: {
    flexDirection: 'row',
    width: Metrics.WIDTH * 0.87,
    alignSelf: 'center',
    marginTop: Metrics.HEIGHT * 0.03,
  },

  countLabelBg: {
    flexDirection: 'column',
    width: Metrics.WIDTH * 0.29,
    justifyContent: 'center',
  },

  countTxt: {
    fontWeight: 'bold',
    color: '#363636',
    fontSize: Fonts.moderateScale(16),
    fontFamily: Fonts.type.SFUIDisplayBold,
    textAlign: 'center',
  },

  labelTxt: {
    color: '#959595',
    fontSize: Fonts.moderateScale(12),
    textAlign: 'center',
  },
  divideVertical: {
    backgroundColor: '#959595',
    width: 1,
    height: Metrics.HEIGHT * 0.05,
    alignSelf: 'flex-end',
    marginBottom: 5,
  },
  modelMain: {
    height: Metrics.HEIGHT,
    width: Metrics.WIDTH,
    justifyContent: 'center',
    alignItems: 'center',
  },
  switchToggleContainer: {
    width: Metrics.HEIGHT * 0.04,
    height: Metrics.HEIGHT * 0.04,
    borderRadius: Metrics.HEIGHT * 0.06,
    borderColor: '#e5e5e5',
    borderWidth: 1,
    shadowOffset: {width: 0, height: 0},
    shadowColor: 'black',
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 2,
  },
  switchToggle: {
    width: Metrics.WIDTH * 0.13,
    height: Metrics.HEIGHT * 0.04,
    borderRadius: 25,
    padding: 0,
  },
  cardLigneText: {
    fontSize: 15,
    fontWeight: 'bold',
    flex: 1,
  },
  logostyle: {
    alignSelf: 'center',
    width: Metrics.WIDTH * 0.28,
    height: Metrics.WIDTH * 0.28,
  },
  headertext: {
    fontFamily: Fonts.PlayfairDisplayBold,
    backgroundColor: 'transparent',
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 30,
    width: Metrics.WIDTH * 0.9,
    color: 'white',
    marginTop: Metrics.HEIGHT * 0.08,
  },
  container: {
    backgroundColor: 'transparent',
    alignItems: 'center',
    height: '100%',
  },

  desctext: {
    fontFamily: Fonts.Bariol,
    backgroundColor: 'transparent',
    textAlign: 'center',
    alignSelf: 'center',
    fontSize: 16,
    width: Metrics.WIDTH * 0.65,
    color: 'white',
    marginTop: Metrics.HEIGHT * 0.04,
  },
  form: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    margin: 20,
    marginTop: Metrics.HEIGHT * 0.05,
  },
  buttonlogin: {
    backgroundColor: Colors.white,
    alignSelf: 'center',
    height: Metrics.HEIGHT * 0.08,
    width: Metrics.WIDTH * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
  },

  buttonsignup: {
    backgroundColor: Colors.yellow,
    alignSelf: 'center',
    height: Metrics.HEIGHT * 0.08,
    width: Metrics.WIDTH * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Metrics.HEIGHT * 0.03,
  },
  buttondialogsignup: {
    backgroundColor: '#4cd964',
    alignSelf: 'center',
    borderRadius: 40,
    height: Metrics.HEIGHT * 0.07,
    width: Metrics.WIDTH * 0.8,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Metrics.HEIGHT * 0.03,
  },

  modelCenter: {
    borderRadius: 5,
    height: Metrics.HEIGHT * 0.48,
    width: Metrics.WIDTH * 0.95,
    backgroundColor: 'white',
    padding: 10,
  },
  close: {
    alignItems: 'flex-end',
  },
  txtsingIn: {
    fontSize: 25,
    fontFamily: Fonts.SFUIDisplayRegular,
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 5,
  },
  item: {
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 8,
    width: Metrics.WIDTH * 0.8,
    height: 40,
  },
  input: {
    fontFamily: 'SFUIDisplay-Regular',
    color: '#b7b7b7',
  },
  rememView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    width: Metrics.WIDTH * 0.8,
    alignSelf: 'center',
  },
  remem: {
    marginLeft: 5,
    fontSize: 15,
    fontFamily: 'SFUIDisplay-Regular',
  },
  forgot: {
    alignSelf: 'flex-end',
    fontSize: 15,
    justifyContent: 'flex-end',
    fontFamily: 'SFUIDisplay-Regular',
  },
  modelSignUp: {
    alignSelf: 'center',
    fontFamily: 'SFUIDisplay-Regular',
    color: 'white',
  },
});
export default styles;
